# Use Golang base image
FROM golang:1.23.3

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy Go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod tidy

# Copy the rest of the application code
COPY . .

# Expose port 8080 for the Go API
EXPOSE 8080

# Run the Go application
CMD ["go", "run", "main.go"]